var app = angular.module('qmgj',['ui.router']);
app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('/home');
	$stateProvider.state('home',{
		//home相当于官网首页
		url:'/home',
		templateUrl:'view/home.html',
		controller:'homeController'
	})
	.state('projectList',{
		url:'/projectList',
		templateUrl:'view/projectList.html',
		controller:'projectListController'
	}).state('login',{
		url:'/login',
		templateUrl:'view/loginView.html',
		controller:'loginController'
	}).state('password',{
        url:'/password',
        templateUrl:'view/password.html',
        controller:'passwordController'
	}).state('register',{
		url:'/register',
		templateUrl:"view/registerView.html",
		controller:"registerController"
	}).state('detail',{
		url:'/detail/:index ',
		templateUrl:'view/detail.html',
		controller:'detailController'
	})
	.state('selfindex',{
		url:'/selfindex',
		templateUrl:'view/selfindex.html',
		controller:'selfindexController'
	})
	.state('selfindex.selfhome',{
		url:'/selfhome',
		templateUrl:'view/selfhome.html'
	})
	.state('selfindex.selfInfo',{
		url:'/selfInfo',
		templateUrl:'view/selfInfo.html'
	}).state('selfindex.selfsecure',{
		url:'/selfsecure',
		templateUrl:'view/selfsecure.html'
	}).state('selfindex.selfcircle',{
		url:'/selfcircle',
		templateUrl:'view/selfcircle.html'
	})
	.state('selfindex.buyRecord',{
		url:'/buyRecord',
		templateUrl:'view/buyRecord.html'
	}).state('fillIn',{
		url:'/fillIn',
		templateUrl:'view/fillIn.html'
	}).state('payPage',{
		url:'/payPage',
		templateUrl:'view/payPage.html'
	}).state('payComplate',{
		url:'/payComplate',
		templateUrl:'view/payComplate.html'
	})
}]);
